### ISSUE TITLE
用这个插件，在微信开发者工具上测试没问题，真机测试时无反应

### ISSUE THREAD

**Issue by muou2125** [cytle/socket.io-mp-client#3]
用这个插件，在微信开发者工具上测试没问题，可以建立连接，但是在真机上测试时发现并没有建立连接，也没有任何报错，求解。  真机： iPhone7 ios11.2

**Comment by swit1983** [comment]
你是怎么引入和连接的啊，代码能看看吗

**Comment by muou2125** [comment]
后面换成小程序提供的API了，没用这个插件了




| |
小生
邮箱：muou2125@163.com
|

签名由 网易邮箱大师 定制

在2018年05月23日 18:14，swit1983 写道：

你是怎么引入和连接的啊，代码能看看吗

**Comment by niices** [comment]
同这个问题

**Comment by jingxinxin** [comment]
@niices 是不是没有换成wss 而是用的ws
