### ISSUE TITLE
本地开发没问题  真机调试的时候会一直发送 xhr 而无法切换到 socket 协议 怎么解决

### ISSUE THREAD

**Issue by niices** [cytle/socket.io-mp-client#4]
这是本地的请求
![image](https://user-images.githubusercontent.com/8327775/42071781-b2fe13a0-7b8f-11e8-803e-52eb450a6352.png)

这是真机调试的时候的请求
![image](https://user-images.githubusercontent.com/8327775/42071794-c50b3e7e-7b8f-11e8-8835-dc22eb7d4122.png)

**Comment by niices** [comment]
微信小程序
基础库版本 2.1.1  2.0.9  1.9.97 1.9.9我刚刚试了都不行

**Comment by cytle** [comment]
如何使用？能写一个小demo吗

**Comment by niices** [comment]
[socket.io.demo.zip](https://github.com/cytle/socket.io-mp-client/files/2147899/socket.io.demo.zip)
写了一个简单的小 demo
第一步引入socket.io-mp
![image](https://user-images.githubusercontent.com/8327775/42075137-0efdac58-7ba2-11e8-92b6-5865aa596bd1.png)
第二步调用
![image](https://user-images.githubusercontent.com/8327775/42075154-2000992a-7ba2-11e8-8b5e-c272939916dc.png)
然后就会发现开发者工具跟远程调试的请求不一样
这是开发者工具的请求
![image](https://user-images.githubusercontent.com/8327775/42075177-3fb04a72-7ba2-11e8-87b6-4212a23034cc.png)
这是远程调试的请求，会一直发送 xhr 请求
![image](https://user-images.githubusercontent.com/8327775/42075197-523fe30a-7ba2-11e8-90f2-6d69691d31fb.png)

**Comment by cytle** [comment]
远程显示是xhr，但实际上的协议已经是wss了，有charles抓的如下

![image](https://user-images.githubusercontent.com/5120505/42218896-9e264cac-7efc-11e8-8e99-23219d509f55.png)

**Comment by cytle** [comment]
这应该是开发者工具的一个问题，直接使用官方的api，在远程调试时也是显示`xhr`

```js
wx.connectSocket({
  url: 'wss://wes.jsustore.cn/socket.io/?EIO=3&transport=websocket',
  data:{
    f: 'wxapp',
  },
});
```

**Comment by jocelc** [comment]
我这里也遇到相同的问题，上报无法成功。
