### ISSUE TITLE
require后直接报错了，麻烦看一下。。

### ISSUE THREAD

**Issue by Gitjinfeiyang** [cytle/socket.io-mp-client#5]
thirdScriptError 
 sdk uncaught third Error 
 require args must be a string 
 Error: require args must be a string
![image](https://user-images.githubusercontent.com/22436151/44777225-99ed7200-abac-11e8-845b-2acb1d2635b6.png)

**Comment by cytle** [comment]
使用的代码发下，不然不知道发生什么错误了

**Comment by cytle** [comment]
是直接引用文件的，还是通过npm

**Comment by Gitjinfeiyang** [comment]
直接引用文件,代码就这样
const io=require("./socketio.js")

**Comment by cytle** [comment]
嗯，发现问题了，已解决~

**Comment by cytle** [comment]
下载最新的`socket.io-mp.js`文件试下
