### ISSUE TITLE
能否增加对transportOptions中extraHeaders的支持？谢谢

### ISSUE THREAD

**Issue by yuan-java** [cytle/socket.io-mp-client#7]
transportOptions: {
        websocket: {
          extraHeaders: {
          }
        }
      },

**Comment by yuan-java** [comment]
另外问一下，支持reconnectionDelayMax等和reconnect有关的参数么？多谢

**Comment by cytle** [comment]
> 能否增加对transportOptions中extraHeaders的支持？

不支持。这个项目只是对`socket.io`使用的`websocket`进行替换，不会去修改实际代码（最低成本，达到最高质量），所以这里额外加一个`websocket ``extraHeaders`参数很难☹️。

> 另外问一下，支持reconnectionDelayMax等和reconnect有关的参数么？多谢

这些`socket.io`的参数都是支持的（免费的）
