### ISSUE TITLE
出现多个connect

### ISSUE THREAD

**Issue by panghaojie** [cytle/socket.io-mp-client#8]
使用环境是小程序
我这边是使用了两个命名空间/control和/chat，代码如下：
zbyIm.cl = io(options.url + '/control', {'transports': ['websocket']});
zbyIm.im = io(options.url + '/chat', {'transports': ['websocket']});

问题是，第一次连接是，是一个connect，如下图：
![image](https://user-images.githubusercontent.com/22138881/49557084-753e2e80-f941-11e8-898a-6214fb51cf2c.png)
断开这个connect后，断开的代码如下：
zbyIm.cl.disconnect();
zbyIm.im.disconnect();

再次连接时，就会出现两个connect，如下图：
![image](https://user-images.githubusercontent.com/22138881/49557202-dbc34c80-f941-11e8-87dc-de772d073b08.png)

**Comment by uikoo9** [comment]
由于小程序限制最多两个socket，所以目前要对接第三方的库有问题，

请问为何第二次connect的时候就会变成两个socket？

**Comment by panghaojie** [comment]
此方法暂时可以解决此问题，即断开连接后，删除命名空间
if (hostname){
       //hostname为服务器域名，注意hostname会加上端口号
	console.log('========nsps', hostname, io.managers);
	nsps = io.managers[hostname+':443']['nsps'];
	delete nsps['/control'];
	delete nsps['/chat'];
}
参考：
使用多路复用：
https://www.w3cschool.cn/socket/socket-k49j2eia.html
删除命名空间：
https://stackoverflow.com/questions/26400595/socket-io-how-do-i-remove-a-namespace
